"""
Report Generator Worker.

This worker formats findings and CVSS scores generated by other workers
and the AI Agent into JSON and PDF deliverables. It performs no reasoning.
"""

import json
import os
import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet


def generate_report(target: str, findings: List[Dict[str, Any]], cvss_scores: List[Dict[str, Any]]) -> Dict[str, str]:
    """
    Generates JSON and PDF reports summarizing the assessment findings.

    Args:
        target: The domain or IP that was assessed.
        findings: List of dicts representing worker outputs and AI summaries.
        cvss_scores: List of dicts containing CVSS score data.

    Returns:
        dict: A dictionary containing paths to the generated PDF and JSON reports,
              or an error dictionary if generation fails.
    """
    try:
        # Generate unique scan identifier
        scan_id = str(uuid.uuid4())
        timestamp = datetime.now(timezone.utc).isoformat()
        
        # Ensure reports directory exists at project root
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
        reports_dir = os.path.join(project_root, 'reports')
        os.makedirs(reports_dir, exist_ok=True)

        json_path = os.path.join(reports_dir, f"{scan_id}.json")
        pdf_path = os.path.join(reports_dir, f"{scan_id}.pdf")

        # Compute overall risk summary tally
        risk_summary = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFORMATIONAL": 0}
        for score in cvss_scores:
            severity = score.get("severity", "INFORMATIONAL").upper()
            if severity in risk_summary:
                risk_summary[severity] += 1
            else:
                risk_summary[severity] = 1 # Catch-all

        # Prepare JSON report
        json_report = {
            "target": target,
            "scan_timestamp": timestamp,
            "overall_risk_summary": risk_summary,
            "findings": findings,
            "cvss_scores": cvss_scores
        }

        # Write JSON to disk
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(json_report, f, indent=2)

        # Generate PDF report
        _generate_pdf(pdf_path, target, timestamp, risk_summary, findings, cvss_scores)

        # Return relative paths as requested
        return {
            "pdf_path": pdf_path,
            "json_path": json_path
        }

    except Exception as e:
        return {
            "error": "Report generation failed",
            "details": str(e)
        }


def _generate_pdf(pdf_path: str, target: str, timestamp: str, risk_summary: Dict[str, int], 
                  findings: List[Dict[str, Any]], cvss_scores: List[Dict[str, Any]]) -> None:
    """Helper method to generate the PDF report using reportlab."""
    doc = SimpleDocTemplate(pdf_path, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = styles['Title']
    story.append(Paragraph("SentinelScan Security Assessment Report", title_style))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"<b>Target:</b> {target}", styles['Normal']))
    story.append(Paragraph(f"<b>Scan Date:</b> {timestamp}", styles['Normal']))
    story.append(Spacer(1, 24))

    # Executive Summary
    story.append(Paragraph("Executive Summary", styles['Heading2']))
    summary_text = (f"This automated assessment targeted {target}. "
                    f"The overall findings indicate {risk_summary.get('CRITICAL', 0)} CRITICAL, "
                    f"{risk_summary.get('HIGH', 0)} HIGH, {risk_summary.get('MEDIUM', 0)} MEDIUM, "
                    f"{risk_summary.get('LOW', 0)} LOW, and {risk_summary.get('INFORMATIONAL', 0)} INFORMATIONAL issues.")
    story.append(Paragraph(summary_text, styles['Normal']))
    story.append(Spacer(1, 24))

    # Findings Section
    story.append(Paragraph("Findings", styles['Heading2']))
    for finding in findings:
        worker_name = finding.get("worker", "Unknown Worker")
        summary = finding.get("summary", "No summary provided.")
        story.append(Paragraph(f"<b>Worker:</b> {worker_name}", styles['Heading3']))
        story.append(Paragraph(summary, styles['Normal']))
        story.append(Spacer(1, 12))

    story.append(Spacer(1, 12))

    # CVSS Scoring Section
    story.append(Paragraph("CVSS Scoring", styles['Heading2']))
    if cvss_scores:
        data = [["Finding", "Vector", "Base Score", "Severity"]]
        
        # Prepare styles based on severity
        severity_colors = {
            "CRITICAL": colors.red,
            "HIGH": colors.red,
            "MEDIUM": colors.orange,
            "LOW": colors.yellow,
            "INFORMATIONAL": colors.lightgrey
        }

        # Background color applied row by row
        table_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ])

        for i, score in enumerate(cvss_scores, start=1):
            sev = score.get("severity", "INFORMATIONAL").upper()
            row = [
                Paragraph(score.get("finding", ""), styles['Normal']),
                Paragraph(score.get("vector", ""), styles['Normal']),
                str(score.get("base_score", "")),
                Paragraph(sev, styles['Normal'])
            ]
            data.append(row)
            
            # Apply color to the severity cell (column 3)
            bg_color = severity_colors.get(sev, colors.white)
            table_style.add('BACKGROUND', (3, i), (3, i), bg_color)
            
        t = Table(data, colWidths=[170, 120, 60, 100])
        t.setStyle(table_style)
        story.append(t)
    else:
        story.append(Paragraph("No scored findings.", styles['Normal']))

    story.append(Spacer(1, 36))
    
    # Footer/Disclaimer
    disclaimer = "This report was generated by an authorized automated assessment tool (SentinelScan)."
    story.append(Paragraph(f"<i>{disclaimer}</i>", styles['Normal']))

    doc.build(story)
